### ISSUE TITLE
Feature Request: Global TAA disable flag/switch

### ISSUE THREAD

**Issue by nknva** [lordbean-git/HQAA#10]
Hi. Many of the games I play are low-poly, or do not have much detail in the first place. While I'd like to try out some of the presets, it seems that TAA provides a very significant _vaseline smeared on goggles_ effect in these, regardless of profile, besides the manual preset where you can disable TAA entirely.

I've been using your older ASSMAA shader for these games, and while it works well, I'm curious if I can tune the full version of HQAA to have less jaggies. Would it be possible for you to add a flag or switch that is always available, regardless of global preset?

**Comment by lordbean-git** [comment]
The global presets largely actually don't do anything differently from the default settings (at least, not for the anti-aliasing). They mostly provide presets for the optional parts of the shader targeted to the bespoke names. The only exception is preset 11, which uses manually configured settings to try to squeeze the best possible balance of performance to quality.

**Comment by nknva** [comment]
Oh, is that so? I was hoping to have an easier reference point of what things should look like using Preset 12 - My games are primarily CPU-limited and text-heavy.

I'll be closing this issue, then - Certainly not required or needed if the presets don't do much.

**Comment by lordbean-git** [comment]
Here's a tip - the difference you're probably seeing stems from the number of passes being used rather than the actual AA settings. If you check the About tab, the shader still shows you how each preset configured the preprocessor settings.
