### ISSUE TITLE
Vertical line

### ISSUE THREAD

**Issue by Chaython** [lordbean-git/HQAA#13]
There is a line running vertically?
Maybe related to GSYNC?
It's constantly moving across the screen.

**Comment by FluffyPuppyKasey** [comment]
Looks like it might be some sort of before and after thing. However I can't verify it because the shader fails to compile after I set HQAA_INTRODUCTION_ACKNOWLEDGED to 1

**Comment by lordbean-git** [comment]
The 30.3 update improves the compiler directives and should not have any problems transitioning from the introduction state to normal use. The moving black line is a before/after comparator, as HQAA runs in a form of demo mode when first loaded.
