### ISSUE TITLE
Use along TAA

### ISSUE THREAD

**Issue by soundsofsilence** [lordbean-git/HQAA#2]
Hey!
HQAA is far better alongside TAA rather than instead of it. Reshade's TAA only functions well during movement; when standing dead still, it might as well not be there. While SMAA/FXAA/HQAA is the opposite, various aliasing effects form around edges as soon as an object moves. Have you ever considered adding a TAA layer to create the ultimate AA? Or simply a temporal-esque layer of the existing SMAA, "a delayed layer" if that makes sense.

**Comment by lordbean-git** [comment]
There's no reason you can't use HQAA with either ReShade's TAA or the TAA built into most games :)

As far as actually building anti-aliasing techniques goes I'm not quite at that level of programming skill yet. Maybe one day.
