### ISSUE TITLE
Fails to compile with DirectX 9 games

### ISSUE THREAD

**Issue by soundsofsilence** [lordbean-git/HQAA#5]
Fails to compile with DirectX 9 games (tested on Fallout New Vegas and Call Of Juarez Gunslinger)
[ReShade.log](https://github.com/lordbean-git/HQAA/files/8169950/ReShade.log)

**Comment by lordbean-git** [comment]
My bad - I know what I did to cause that. Fix will be available shortly.

**Comment by lordbean-git** [comment]
Patched version now available. Compiles on Borderlands TPS on my system, let me know if you have any problems with it.

**Comment by soundsofsilence** [comment]
works now! thanks!
