### ISSUE TITLE
Use the improved FAAA edge detection algorithm

### ISSUE THREAD

**Issue by ghost** [lordbean-git/HQAA#6]
https://github.com/grebord/Fast-Adaptive-AA
In every instance of this vs normal FXAA, FAAA produces far less dithering, artifacts & unwanted antialiasing/blur, at the same if not better performance. This algorithm also is very adept at not antialiasing text.
It doesn't _miss_ any actual aliasing, it's like black magic. 
For even higher quality results, you could try converting it to chroma instead of luma.

**Comment by lordbean-git** [comment]
The FXAA inside HQAA is already more similar to FAAA than original FXAA by comparison. Remember, HQAA doesn't use stock code for SMAA and FXAA - I've modified it quite a lot at this point.
