### ISSUE TITLE
Appreciate all the effort you put in! Lovely shader.

### ISSUE THREAD

**Issue by kindevall** [lordbean-git/HQAA#8]
Not an issue or anything, quite the opposite actually. Really wanted to make a simple appreciation post. Been using this shader for quite a while now in a couple of games, and am always happy to see almost _daily(!)_ updates to the shader. Although definitely not the lightest, but might be one of the best/most robust (multipurpose?) AA-shaders out there. Respect the effort you put in, excited to see how the shader keeps on evolving. 😄

**Comment by lordbean-git** [comment]
Thanks, I've enjoyed building it. It's pretty much done now for most intents and purposes, though I'm still fine tuning a few things here and there.
