### ISSUE TITLE
Depth/color edge detection

### ISSUE THREAD

**Issue by soundsofsilence** [lordbean-git/HQAA#9]
Is there a Depth/color/lum detection mode switch? I can't find it
It's a simple option that radically alters the end result
Thanks!
Keep being awesome!

**Comment by lordbean-git** [comment]
No, there isn't. HQAA is built not to use the depth buffer to maintain full compatibility with online games. Also, the edge detection method being used is neither color or luma - it uses chroma edge detection (this is similar to color, but more advanced) to ensure it picks up as much data as possible.

**Comment by soundsofsilence** [comment]
I see. Would you consider adding a toggleable depth buffer option? In my experience, it's usually the preferable option.

**Comment by lordbean-git** [comment]
I have no plans to do so. HQAA's edge detection method is very flexible if you configure it using advanced mode, and should be able to spot just about anything that constitutes an edge generally. It's possible you might need to try this if you are using it in a game that is, on average, very dark - the basic quality profiles use dynamic thresholding enough to cover games with a wide luma range, but not necessarily games with an extremely low average luma.
